apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # The port to the service itself (usually 80 or 443 for a standard web service)
      targetPort: 8080 # The port on the Pod that the service should forward to (what is specified in app.js)